export const walletConstants = {
    CONNECT_REQUEST: 'WALLET_CONNECT_REQUEST',
    CONNECT_SUCCESS: 'WALLET_CONNECT_SUCCESS',
    CONNECT_FAILURE: 'WALLET_CONNECT_FAILURE',
    DISCONNECT_REQUEST: 'WALLET_DISCONNECT_REQUEST',
    BUY_SUCCESS: 'WALLET_BUY_SUCCESS',
    BUY_FAILURE: 'WALLET_CONNECT_FAILURE'
    
  };