export const walletConstants = {
    CONNECT_REQUEST: 'WALLET_CONNECT_REQUEST',
    CONNECT_SUCCESS: 'WALLET_CONNECT_SUCCESS',
    CONNECT_FAILURE: 'WALLET_CONNECT_FAILURE',
    DISCONNECT_REQUEST: 'WALLET_DISCONNECT_REQUEST',
    BUY_RESULT: 'WALLET_BUY_RESULT',
    CLEAR_BUY_RESULT: 'WALLET_CLEAR_BUY_RESULT',
    
  };